Codigo/ControlPlanilla/ControlPlanilla/Controllers/PayrollJournalController.cs
using DevExpress.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlPlanilla.Controllers
{
    public class PayrollJournalController : GlobalFunctions
    {
        // GET: PayrollJournal
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult ListaTable(string No, string codefilter, string idtemplate)
        {
            if (ModelState.IsValid)
            {
                decimal temp = MethodStep382(No, codefilter, idtemplate);
                var result = 1;
                ViewBag.OpcionConsulta = 1;
                ViewBag.employee = No;
                ViewBag.prc = codefilter;
                ViewBag.stpe1 = "ADD BASE AMOUNT";
                ViewBag.pra1 = 0;
                ViewBag.ta1 = Math.Round(MethodStep220(No, codefilter, idtemplate), 2);
                ViewBag.stpe2 = "AMOUNT IS EMP RATE";
                ViewBag.pra2 = Math.Round(MethodStep22(No, codefilter, idtemplate), 2);
                ViewBag.ta2 = 0;
                ViewBag.stpe3 = "AMOUNT TIMES QTY";
                ViewBag.pra3 = Math.Round(MethodStep255(No, codefilter, idtemplate), 2);
                ViewBag.ta3 = 0;
                ViewBag.stpe4 = "AMOUNT TIMES TAXABLE";
                ViewBag.pra4 = Math.Round(MethodStep382(No, codefilter, idtemplate), 2);
                ViewBag.ta4 = 0;
                actualizarpayrolljournalline(No, codefilter, idtemplate,  Convert.ToString( ViewBag.pra4));
                return PartialView(result);
            }

            return View();
        }


        ControlPlanilla.Models.PlanillaPayControls db = new ControlPlanilla.Models.PlanillaPayControls();
        [ValidateInput(false)]
        public ActionResult GridViewPartial1(string Employee_No)
        {
            var model = db.PayrollJournalLine.Where(s => s.EmployeeNo == Employee_No);
            if (model.Count() == 0)
            {
               
                model = db.PayrollJournalLine;
            }
            return PartialView("_GridViewPartial", model.ToList());
        }


        [HttpPost]
        [AllowAnonymous]
        public ActionResult GridViewPartial(string Employee_No)
        {
            var model = db.PayrollJournalLine.Where(s => s.EmployeeNo == Employee_No);
            if (model.Count() == 0)
            {
                model = db.PayrollJournalLine;
            }
            return PartialView("_GridViewPartial", model.ToList());
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult GridViewPartialAddNew([ModelBinder(typeof(DevExpressEditorsBinder))] ControlPlanilla.Models.PayrollJournalLine item)
        {
            var model = db.PayrollJournalLine;
            if (ModelState.IsValid)
            {
                try
                {
                    item.PayrollRunNoSeries = item.JournalTemplateName;
                    
                    model.Add(item);
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            return PartialView("_GridViewPartial", model.ToList());
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult GridViewPartialUpdate([ModelBinder(typeof(DevExpressEditorsBinder))] ControlPlanilla.Models.PayrollJournalLine item)
        {
            var model = db.PayrollJournalLine;
                            try
                {
                    var modelItem = model.FirstOrDefault(it => it.JournalTemplateName == item.JournalTemplateName &&  it.LineNumber==item.LineNumber);
                    if (modelItem != null)
                    {
                        modelItem.PayrollAmount = item.PayrollAmount;
                        modelItem.TaxableAmount = item.TaxableAmount;
                        modelItem.PayrollPostingGroup = item.PayrollPostingGroup == null ? "": item.PayrollPostingGroup;
                        db.Entry(modelItem).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            
            return PartialView("_GridViewPartial", model.ToList());
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult GridViewPartialDelete(System.String JournalTemplateName)
        {
            var model = db.PayrollJournalLine;
            if (JournalTemplateName != null)
            {
                try
                {
                    var item = model.FirstOrDefault(it => it.JournalTemplateName == JournalTemplateName);
                    if (item != null)
                        model.Remove(item);
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            return PartialView("_GridViewPartial", model.ToList());
        }
    }
}

Codigo/ControlPlanilla/ControlPlanilla/Views/PayrollJournal/Index.cshtml
@*@model IEnumerable<ControlPlanilla.Models.ListaDocumentosView>*@

@{
    ViewBag.Title = "Documentos Adjuntos";
    Layout = "~/Views/Shared/_Vista.cshtml";
}

<br />
<h3>Payroll Journal</h3>
<div class="row">
    <div class="col-sm-3">
        <div class="form-group">
            <label> Payroll Journal Template</label>
        </div>
    </div>
    <div class="col-sm-9">
        <div class="form-group">
            <select id="id_template" name="descripcion" class="form-control col-md-12">
                <option value="">--Seleccione una opción--</option>
                <option value="CONSTANCIA">Diario de Constancia</option>
                <option value="LIQUIDA">Planilla Liquidación</option>
                <option value="PLANI SPS">Planilla DEMO San Pedro Sula</option>
                <option value="VACASION">Planilla vacación</option>
            </select>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-3">
        <div class="form-group">
            <label>Payroll Control Code Filter </label>
        </div>
    </div>
    <div class="col-sm-9">
        <div class="form-group">
            <select id="code_filter" name="code_filter" class="form-control col-md-12">
                <option value="">--Seleccione una opción--</option>
                <option value="SUELDOQ">SUELDOQ</option>
            </select>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-3">
        <div class="form-group">
            <label>No de Empleado</label>
        </div>
    </div>
    <div class="col-sm-9">
        <div class="form-group">
            <input type="text" id="No_empleado" class="form-control" placeholder="Opcional" />
        </div>
    </div>
</div>
<br />
<div class="form-group">
    <div class="col-md-2">
        <button id="btn_calculate" class="btn btn-primary" type="button">Calcular</button>
    </div>
</div>
<br />
<div class="col-sm-12 overflow-auto" style="width:1200px;" id="ListaTable" name="ListaTable">

</div>
<div class="col-sm-12 overflow-auto" style="width:1200px;" id="ListaTable1" name="ListaTable1">

    @Html.Action("GridViewPartial1")

    <br />
</div>

<!--Botones-->
<div class="btn-group btn-group" id="grpBotones" style="text-align:center">
    <button class="btn btn-primary" id="btnCrearArchivo" name="btnCrearArchivo" onclick="Crear()">Adicionar</button>
    <button class="btn btn-primary" id="btnModificarArchivo" name="btnModificarArchivo" onclick="Modificar()">Modificar</button>
    <button class="btn btn-primary" id="btnEliminarArchivo" name="btnEliminarArchivo" onclick="Eliminar()">Eliminar</button>
    <button class="btn btn-primary" onclick="Nuevo()">Nuevo</button>
</div>

<br />


<style>
    /* Efecto de mano en el puntero en la tabla tListaDocumentos */
    td {
        border: 1px #DDD solid;
        padding: 5px;
        cursor: pointer;
    }

    /* Sobreado al seleccionar una fila de la tabla tListaDocumentos */
    .selected {
        background-color: lightgray;
        color: black;
    }

    /*Modificar la vista previa de PDFs*/
    .pdfobject-container {
        height: 45rem;
        border: 1rem solid rgba(0,0,0,.1);
    }
</style>

<script>
    var TmpPath = ""; //Almacena la ruta temporal para poder hacer la vista previa de archivos (imagen o pdf)
    var IdAdjunto = 0; // Para la modificacion o eliminacion de archivos
    var CdOpcionSistema;
    var CdForaneo;
    var DsForaneo;
    window.onload = function ()
    {
        //funciones a ejecutar
        $('#grpBotones').css('display', 'none');
        $.unblockUI();
        //CargarListaDocumentos();
    };
     // Escuchamos el evento 'change' del input donde cargamos el archivo
    $(document).on('change', 'input[type=file]', function (e) {
        // Obtenemos la ruta temporal mediante el evento
        TmpPath = URL.createObjectURL(e.target.files[0]);
    });
    $(document).ready(function () {
        $("#btn_calculate").click(function () {
            No = $('#No_empleado').val();
            Codefilter = $('#code_filter').val();
            IdTemplate = $('#id_template').val();

            Calculate220(No, Codefilter, IdTemplate);

        })

        $("#No_empleado").change(function () {
            //CargarJournal();
        });


     });

    function Calculate220(No, codefilter,idtemplate)
    {

        url = '@Url.Action("ListaTable", "PayrollJournal")';
        var data = { No: No, codefilter: codefilter, idtemplate: idtemplate };

        $.post(url, data).done(function (result) {
            $('#ListaTable').html('');
            $('#ListaTable').html(result);
            $.unblockUI();
        });

    }
    function CargarListaDocumentos() {
        $.blockUI();
        cadenaBinaria = "";

        var opcionConsulta = 2

        var url = '@Url.Action("ListaDocumentos", "PayrollJournal")';
        var data = { OpcionConsulta : opcionConsulta };

         $.post(url, data).done(function (result) {
             $('#ListaTable').html('');
             $('#ListaTable').html(result);
                $.unblockUI();
         });
    }



    function CargarJournal() {
        $.blockUI();
        cadenaBinaria = "";
        Employee_No = $('#No_empleado').val();

        var url = '@Url.Action("GridViewPartial", "PayrollJournal")';
        var data = { Employee_No: Employee_No };

        $.post(url, data).done(function (result) {
            $.unblockUI();
             $('#ListaTable1').html('');
             $('#ListaTable1').html(result);

         });
    }
</script>

Codigo/ControlPlanilla/ControlPlanilla/Views/PayrollJournal/ListaTable.cshtml
    <div class="table-responsive" style="padding:15px">

        <table class="table table-bordered" id="tListaTable">

            <thead>
                <tr>
                    <th>Employee No.</th>
                    <th>Payroll Control</th>
                    <th>Method Step Code</th>
                    <th>Payroll Amount</th>
                    <th>Taxable Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr><td>@ViewBag.employee</td><td>@ViewBag.prc</td><td>@ViewBag.stpe1</td><td>@ViewBag.pra1<td>@ViewBag.ta1</td></tr>
                <tr><td>@ViewBag.employee</td><td>@ViewBag.prc</td><td>@ViewBag.stpe2</td><td>@ViewBag.pra2<td>@ViewBag.ta2</td></tr>
                <tr><td>@ViewBag.employee</td><td>@ViewBag.prc</td><td>@ViewBag.stpe3</td><td>@ViewBag.pra3<td>@ViewBag.ta3</td></tr>
                <tr><td>@ViewBag.employee</td><td>@ViewBag.prc</td><td>@ViewBag.stpe4</td><td>@ViewBag.pra4<td>@ViewBag.ta4</td></tr>
            </tbody>


        </table>

    </div>

        

Codigo/ControlPlanilla/ControlPlanilla/Views/PayrollJournal/_GridViewPartial.cshtml
@{
    var grid = Html.DevExpress().GridView(settings =>
    {
        settings.Name = "GridView";
        settings.CallbackRouteValues = new
        {
            Controller = "PayrollJournal",
            Action = "GridViewPartial" };
        settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "PayrollJournal", Action = "GridViewPartialAddNew" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "PayrollJournal", Action = "GridViewPartialUpdate" };
        settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;
        settings.SettingsBehavior.ConfirmDelete = true;

        settings.CommandColumn.Visible = true;
        settings.CommandColumn.ShowNewButton = true;
        settings.CommandColumn.ShowDeleteButton = false;
        settings.CommandColumn.ShowEditButton = true;

        settings.KeyFieldName = "JournalTemplateName;LineNumber";

        settings.SettingsPager.Visible = true;
        settings.Settings.ShowGroupPanel = true;
        settings.Settings.ShowFilterRow = true;
        settings.SettingsBehavior.AllowSelectByRowClick = true;

        settings.SettingsAdaptivity.AdaptivityMode = GridViewAdaptivityMode.HideDataCellsWindowLimit;
        settings.SettingsAdaptivity.AdaptiveColumnPosition = GridViewAdaptiveColumnPosition.Right;
        settings.SettingsAdaptivity.AdaptiveDetailColumnCount = 1;
        settings.SettingsAdaptivity.AllowOnlyOneAdaptiveDetailExpanded = false;
        settings.SettingsAdaptivity.HideDataCellsAtWindowInnerWidth = 0;
        settings.SettingsEditing.ShowModelErrorsForEditors = false;

        settings.Columns.Add( "EmployeeNo");
        settings.Columns.Add(column => {
            column.EditorProperties().DateEdit(p =>
            {
                p.EditFormatString = "yyyy/MM/dd";
                p.DisplayFormatString = "yyyy/MM/dd";
            });
            column.FieldName = "PostingDate";
        });
        settings.Columns.Add("DocumentType");
        settings.Columns.Add("DocumentNo");
        settings.Columns.Add(column =>
        {
            column.EditorProperties().DateEdit(p =>
            {
                p.EditFormatString = "yyyy/MM/dd";
                p.DisplayFormatString = "yyyy/MM/dd";
            });
            column.FieldName = "PayPeriodEndDate";
        });

        settings.Columns.Add("PayCycleCode");
        settings.Columns.Add("PayrollControlCode");
        settings.Columns.Add("PayrollAmount");
        settings.Columns.Add("TaxableAmount");
        settings.Columns.Add("EmployeeName");
        settings.Columns.Add("PayrollControlType");
        settings.Columns.Add("RegularPay");
        settings.Columns.Add("EmployerNo");
        settings.Columns.Add("DimensionSetID");
        settings.Columns.Add("PayrollPostingGroup");
        settings.Columns.Add("JournalTemplateName");
        settings.Columns.Add("LineNumber");
        settings.Columns.Add("JournalBatchName");
        settings.Columns.Add("PayCycleTerm");
    });
    if (ViewData["EditError"] != null)
    {
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()