Codigo/ControlPlanilla/ControlPlanilla/Models/GLB_CONF_OPCI_SIST.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLB_CONF_OPCI_SIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GLB_CONF_OPCI_SIST()
        {
            this.GLB_OPCI_SIST_PERFIL = new HashSet<GLB_OPCI_SIST_PERFIL>();
        }
    
        public string CD_CODI_SIST { get; set; }
        public string CD_CODI_MENU { get; set; }
        public string CD_CODI_OPCI_SIST { get; set; }
        public string CD_EMPRESA { get; set; }
        public int NM_SEQU_ORDE_SIST { get; set; }
        public int NM_SEQU_ORDE_MENU { get; set; }
        public int NM_SEQU_ORDE_OPCI { get; set; }
        public string USUA_CREA { get; set; }
        public System.DateTime FECH_CREA { get; set; }
        public string USUA_ACTU { get; set; }
        public Nullable<System.DateTime> FECH_ACTU { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual GLB_MENUS_SISTEMAS GLB_MENUS_SISTEMAS { get; set; }
        public virtual GLB_OPCIONES_SISTEMA GLB_OPCIONES_SISTEMA { get; set; }
        public virtual GLB_SISTEMAS GLB_SISTEMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLB_OPCI_SIST_PERFIL> GLB_OPCI_SIST_PERFIL { get; set; }
    }
}

Codigo/ControlPlanilla/ControlPlanilla/Models/GLB_CONF_OPCI_SISTView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ControlPlanilla.Models
{
    public partial class GLB_CONF_OPCI_SISTView
    {
        public string CD_CODI_SIST { get; set; }
        public string CD_CODI_MENU { get; set; }
        public string CD_CODI_OPCI_SIST { get; set; }
        public string CD_EMPRESA { get; set; }
        public int NM_SEQU_ORDE_SIST { get; set; }
        public int NM_SEQU_ORDE_MENU { get; set; }
        public int NM_SEQU_ORDE_OPCI { get; set; }
        public string USUA_CREA { get; set; }
        public System.DateTime FECH_CREA { get; set; }
        public string USUA_ACTU { get; set; }
        public Nullable<System.DateTime> FECH_ACTU { get; set; }
        public Nullable<bool> Estado { get; set; }

    }
}

Codigo/ControlPlanilla/ControlPlanilla/Controllers/GLB_CONF_OPCI_SISTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Core.Objects;
using ControlPlanilla.Models;
using System.Data.Entity;

namespace ControlPlanilla.Controllers
{
    public class GLB_CONF_OPCI_SISTController : AuditoriaController
    {
        // GET: GLB_CONF_OPCI_SIST
        static string idMenu;

        [ValidateInput(false)]
        public ActionResult BuscarID(string key)
        {
            idMenu = key;
            if (key != "" || key == null) {
                key = "something";
            }
            return RedirectToAction("Index", new { id = key });
        }
        public JsonResult ObtenerMenus(string CD_CODI_OPCI_SISTT)
        
        {
            
            var resultspli = idMenu.Split('|');
            string CD_CODI_SIST = resultspli[0];
            string CD_CODI_MENU = resultspli[1];
            string CD_CODI_OPCI_SIST = resultspli[2];
            var listaEmployee = db.GLB_CONF_OPCI_SIST.Where(ep =>ep.CD_CODI_SIST== CD_CODI_SIST && ep.CD_CODI_MENU== CD_CODI_MENU &&   ep.CD_CODI_OPCI_SIST == CD_CODI_OPCI_SIST).
                Select(r => new GLB_CONF_OPCI_SISTView
                {
                    CD_CODI_SIST = r.CD_CODI_SIST,
                    CD_CODI_MENU = r.CD_CODI_MENU,
                    CD_CODI_OPCI_SIST = r.CD_CODI_OPCI_SIST,
                    Estado = r.Estado,
                }).ToList();
            var listFinal = listaEmployee;
            return Json(listFinal, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index(string id)
        {
            if (id != null)
            {
                ViewBag.idseleccinado = id;
            }
            var listaSistemas =  from modulo in db.GLB_SISTEMAS
                                where modulo.CD_ESTADO_SISTEMA == true
                                 select new GLB_SISTEMASView { CD_CODI_SIST = modulo.CD_CODI_SIST, DS_NOMB_SIST = modulo.DS_NOMB_SIST };
            var listaMenus = from menus in db.GLB_MENUS_SISTEMAS
                             where menus.CD_ESTADO_MENU == true
                             select new GLB_MENUS_SISTEMASView { CD_CODI_MENU = menus.CD_CODI_MENU, DS_DESC_MENU = menus.DS_DESC_MENU };
            var listaSubMenus = from submenus in db.GLB_OPCIONES_SISTEMA
                                where submenus.CD_ESTADO_OPCION_SISTEMA == true
                                select new GLB_OPCIONES_SISTEMAView { CD_CODI_OPCI_SIST = submenus.CD_CODI_OPCI_SIST, DS_NOMBRE_FORMA = submenus.DS_NOMBRE_FORMA };
            ViewBag.Sistema = listaSistemas.ToList();
            ViewBag.Menu = listaMenus.ToList();
            ViewBag.Modulo = listaSubMenus.ToList();
            return View();
        }
        
        ControlPlanilla.Models.PlanillaAccesoMenus db = new ControlPlanilla.Models.PlanillaAccesoMenus();
        [ValidateInput(false)]
        public ActionResult GridViewPartial()
        {
            var model = from principal in db.GLB_CONF_OPCI_SIST
                        join sistema in db.GLB_SISTEMAS on principal.CD_CODI_SIST equals sistema.CD_CODI_SIST
                        join menu in db.GLB_MENUS_SISTEMAS on principal.CD_CODI_MENU equals menu.CD_CODI_MENU
                        join opcion in db.GLB_OPCIONES_SISTEMA on principal.CD_CODI_OPCI_SIST equals opcion.CD_CODI_OPCI_SIST
                        select new { CD_CODI_SIST = principal.CD_CODI_SIST, CD_CODI_MENU = principal.CD_CODI_MENU, CD_CODI_OPCI_SIST = principal.CD_CODI_OPCI_SIST, DS_NOMB_SIST = sistema.DS_NOMB_SIST, DS_DESC_MENU = menu.DS_DESC_MENU, DS_NOMBRE_FORMA = opcion.DS_NOMBRE_FORMA, Estado = principal.Estado };
            return PartialView("_GridViewPartial", model.ToList());
        }

        [ValidateInput(false)]
        public ActionResult datosGenerales(Int32 pageSize  = 5)
        {
            var model = from principal in db.GLB_CONF_OPCI_SIST
                        join sistema in db.GLB_SISTEMAS on principal.CD_CODI_SIST equals sistema.CD_CODI_SIST
                        join menu in db.GLB_MENUS_SISTEMAS on principal.CD_CODI_MENU equals menu.CD_CODI_MENU
                        join opcion in db.GLB_OPCIONES_SISTEMA on principal.CD_CODI_OPCI_SIST equals opcion.CD_CODI_OPCI_SIST
                        select new { CD_CODI_SIST = principal.CD_CODI_SIST, CD_CODI_MENU = principal.CD_CODI_MENU, CD_CODI_OPCI_SIST = principal.CD_CODI_OPCI_SIST,   DS_NOMB_SIST = sistema.DS_NOMB_SIST, DS_DESC_MENU=menu.DS_DESC_MENU, DS_NOMBRE_FORMA=opcion.DS_NOMBRE_FORMA, Estado=principal.Estado };

            return PartialView("_GridViewPartial", model.ToList());
        }
        //
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Create_Opcion(string CD_CODI_SIST, string CD_CODI_MENU, string CD_CODI_OPCI_SIST,  string Estado,int NM_SEQU_ORDE_SIST=1, int NM_SEQU_ORDE_MENU=2,int NM_SEQU_ORDE_OPCI=4)
        {
            if (CD_CODI_SIST != "")
            {
                GLB_CONF_OPCI_SIST grabar;
                //validar si existe
                var existincia = (from e in db.GLB_CONF_OPCI_SIST
                                  where e.CD_CODI_SIST == CD_CODI_SIST && e.CD_CODI_MENU== CD_CODI_MENU && e.CD_CODI_OPCI_SIST== CD_CODI_OPCI_SIST
                                  select e.CD_CODI_SIST).Count();

                if (existincia > 0)
                {
                    grabar = db.GLB_CONF_OPCI_SIST.Find(CD_CODI_SIST, CD_CODI_MENU, CD_CODI_OPCI_SIST);
                }
                else
                {
                    grabar = new GLB_CONF_OPCI_SIST();
                }

                grabar.CD_CODI_SIST = CD_CODI_SIST;
                grabar.CD_EMPRESA = CdEmpresa;
                grabar.Estado = Convert.ToBoolean(Estado);
                grabar.CD_CODI_MENU = CD_CODI_MENU;
                grabar.CD_CODI_OPCI_SIST = CD_CODI_OPCI_SIST;
                grabar.CD_CODI_MENU = CD_CODI_MENU;
                grabar.NM_SEQU_ORDE_SIST = NM_SEQU_ORDE_SIST;
                grabar.NM_SEQU_ORDE_MENU = NM_SEQU_ORDE_MENU;
                grabar.NM_SEQU_ORDE_OPCI = NM_SEQU_ORDE_OPCI;
                grabar.FECH_CREA = Ahora;
                grabar.USUA_CREA = Usuario;

                if (existincia > 0)
                {
                    db.Entry(grabar).State = EntityState.Modified;
                }
                else
                {
                    db.GLB_CONF_OPCI_SIST.Add(grabar);
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

    }
}

Codigo/ControlPlanilla/ControlPlanilla/Views/GLB_CONF_OPCI_SIST/Index.cshtml
<br />
<h3>Mantenimiento Sistema</h3>
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active" id="DatosGenerales-tab" data-toggle="tab" href="#DatosGenerales" role="tab" aria-controls="DatosGenerales" aria-selected="true">Datos generales</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link" id="Detalles-tab" data-toggle="tab" href="#Detalles" role="tab" aria-controls="Detalles" aria-selected="false">Detalles</a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="DatosGenerales" role="tabpanel" aria-labelledby="DatosGenerales-tab">
        <br />
        <div class="overflow-auto" style="height:400px;">
            @Html.Action("GridViewPartial")
        </div>
    </div>
    <div class="tab-pane fade" id="Detalles" role="tabpanel" aria-labelledby="Detalles-tab">
        <br />
        <div class="row">
            <div class="col-sm-3">
                <div class="form-group">
                    <label id="lblmodulo">Modulo</label>
                </div>
                </div>
            <div class="col-md-9">
                <div class="form-group">
                    <select id="cdmodulo" name="cdmodulo" class="form-control">
                        <option value="0">Seleccione una opción</option>
                        @foreach (var item in ViewBag.Sistema)
                        {
                            <option value="@item.CD_CODI_SIST">@item.DS_NOMB_SIST</option>
                        }
                    </select>
                </div>
                </div>
            </div>
        <div class="row">
            <div class="col-sm-3">
                <div class="form-group">
                    <label id="lblmenu">Menú</label>
                </div>
                </div>
            <div class="col-md-9">
                <div class="form-group">
                    <select id="cdmenu" name="cdmenu" class="form-control">
                        <option value="0">Seleccione una opción</option>
                        @foreach (var item in ViewBag.Menu)
                        {
                            <option value="@item.CD_CODI_MENU">@item.DS_DESC_MENU</option>
                        }
                    </select>
                </div>
                </div>
            </div>
        <div class="row">
            <div class="col-sm-3">
                <div class="form-group">
                    <label id="lblsubmenu">Submenú</label>
                </div>
                </div>
            <div class="col-md-9">
                <div class="form-group">
                    <select id="cdsubm" name="cdsubm" class="form-control">
                        <option value="0">Seleccione una opción</option>
                        @foreach (var item in ViewBag.Modulo)
                        {
                            <option value="@item.CD_CODI_OPCI_SIST">@item.DS_NOMBRE_FORMA</option>
                        }
                    </select>
                </div>
                </div>
            </div>
        <div class="row">
            <div class="col-sm-3">
                <div class="form-group">
                    <label id="lblestado">Estado</label>
                </div>
                </div>
            <div class="col-sm-9">
                <div class="form-group">
                    <input type="radio" id="activo" name="EstadoModulo" value="true" /> Activo
                    <input type="radio" id="activo" name="EstadoModulo" value="false" /> Inactivo
                </div>
                </div>
            </div>

        <br />
        <div class="form-group">
            <button class="btn btn-primary" id="limpiar" type="button">Limpiar</button>
            <button class="btn btn-primary" id="guardar" type="button">Guardar</button>
        </div>
    </div>
</div>
<br />


<script type="text/javascript">
     $(function () {
        if ('@ViewBag.MensajeOk' != '') {
            toastr.success('@ViewBag.MensajeOk');
        }
        if ('@ViewBag.MensajeAlerta' != '') {
            toastr.warning('@ViewBag.MensajeAlerta');
        }
        if ('@ViewBag.MensajeError' != '') {
            toastr.warning('@ViewBag.MensajeError');
        }
    });

         function Create_Opcion(CD_CODI_SIST, CD_CODI_MENU, CD_CODI_OPCI_SIST,  Estado) {
        url = '@Url.Action("Create_Opcion", "GLB_CONF_OPCI_SIST")';
        var data = { CD_CODI_SIST: CD_CODI_SIST, CD_CODI_MENU: CD_CODI_MENU, CD_CODI_OPCI_SIST: CD_CODI_OPCI_SIST, Estado: Estado};
        $.post(url, data).done(function (result) {
            toastr.success("Exitoso");
        });
    }


    //
    $(document).ready(function () {

        $("#guardar").click(function () {
            CD_CODI_SIST = $('#cdmodulo').val();
            CD_CODI_MENU = $('#cdmenu').val();
            CD_CODI_OPCI_SIST = $('#cdsubm').val();
            Estado = $("input[name='EstadoModulo']:checked").val();
            Create_Opcion(CD_CODI_SIST, CD_CODI_MENU, CD_CODI_OPCI_SIST, Estado);
        });
        $("#limpiar").click(function () {
            LimpiarInfo();
        })
        if ('@ViewBag.idseleccinado') {
            CargarInfo('@ViewBag.idseleccinado');
        }
    });

   //cargar cliente
    function CargarInfo(CD_CODI_OPCI_SIST) {
        url = '@Url.Action("ObtenerMenus", "GLB_CONF_OPCI_SIST")';
        var data = { CD_CODI_OPCI_SIST: CD_CODI_OPCI_SIST };

        $.post(url, data).done(function (result) {
            for (var i = 0; i < result.length; i++) {
                document.getElementById("cdmodulo").value = result[i].CD_CODI_SIST;
                document.getElementById("cdmenu").value = result[i].CD_CODI_MENU;
                document.getElementById("cdsubm").value = result[i].CD_CODI_OPCI_SIST;
                $("input[name=EstadoModulo][value=" + result[i].Estado + "]").prop('checked', true);
                $('.nav-tabs a[href="#Detalles"]').tab('show');
            }
        });
    }
    //limpiar
    function LimpiarInfo() {
        document.getElementById('cdmodulo').innerHTML = "0";
        document.getElementById('cdmenu').innerHTML = "0";
        document.getElementById('cdsubm').innerHTML = "0";
        $("input[name=EstadoModulo][value=true]").prop('checked', true);
    }
</script>

Codigo/ControlPlanilla/ControlPlanilla/Views/GLB_CONF_OPCI_SIST/_GridViewPartial.cshtml
@{
    var grid = Html.DevExpress().GridView(settings =>
    {
        settings.Name = "GridView3";
        settings.CallbackRouteValues = new { Controller = "GLB_CONF_OPCI_SIST", Action = "datosGenerales" };
        settings.CommandColumn.CustomButtons.Add(new GridViewCommandColumnCustomButton() { ID = "btn", Text = "Editar" });
        settings.ClientSideEvents.CustomButtonClick = "function(s, e) { document.location='" + DevExpressHelper.GetUrl(new { Controller = "GLB_CONF_OPCI_SIST", Action = "BuscarID" }) + "?key=' + s.GetRowKey(e.visibleIndex); }";
        settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;
        settings.SettingsBehavior.ConfirmDelete = true;

        settings.CommandColumn.Visible = true;
        

        settings.KeyFieldName = "CD_CODI_SIST;CD_CODI_MENU;CD_CODI_OPCI_SIST";

        settings.SettingsPager.Visible = true;
        settings.Settings.ShowGroupPanel = true;
        settings.Settings.ShowFilterRow = true;
        settings.SettingsBehavior.AllowSelectByRowClick = true;
        settings.Theme = "Office2010Blue";

        settings.SettingsAdaptivity.AdaptivityMode = GridViewAdaptivityMode.Off;
        settings.SettingsAdaptivity.AdaptiveColumnPosition = GridViewAdaptiveColumnPosition.Right;
        settings.SettingsAdaptivity.AdaptiveDetailColumnCount = 1;
        settings.SettingsAdaptivity.AllowOnlyOneAdaptiveDetailExpanded = true;
        settings.SettingsAdaptivity.HideDataCellsAtWindowInnerWidth = 0;

        settings.Columns.Add("CD_CODI_SIST");
        settings.Columns.Add("CD_CODI_MENU").Visible = false;
        settings.Columns.Add("CD_CODI_OPCI_SIST").Visible = false;
        settings.Columns.Add("DS_NOMB_SIST");
        settings.Columns.Add("DS_DESC_MENU");
        settings.Columns.Add("DS_NOMBRE_FORMA");
        settings.Columns.Add("Estado");
    });
    if (ViewData["EditError"] != null)
    {
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()