Codigo/ControlPlanilla/ControlPlanilla/Models/FormatoPlanilla.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPlanilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormatoPlanilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormatoPlanilla()
        {
            this.FormatoPlanillaDetalleEgresos = new HashSet<FormatoPlanillaDetalleEgresos>();
            this.FormatoPlanillaDetalleIngresos = new HashSet<FormatoPlanillaDetalleIngresos>();
            this.FormatoPlanillaEncabezadoEgresos = new HashSet<FormatoPlanillaEncabezadoEgresos>();
            this.FormatoPlanillaEncabezadoIngresos = new HashSet<FormatoPlanillaEncabezadoIngresos>();
        }
    
        public string ID_FORMATO { get; set; }
        public string DESCRIPCION { get; set; }
        public string USUA_CREA { get; set; }
        public System.DateTime FECH_CREA { get; set; }
        public string USUA_ACTUA { get; set; }
        public Nullable<System.DateTime> FECH_ACTUA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormatoPlanillaDetalleEgresos> FormatoPlanillaDetalleEgresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormatoPlanillaDetalleIngresos> FormatoPlanillaDetalleIngresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormatoPlanillaEncabezadoEgresos> FormatoPlanillaEncabezadoEgresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormatoPlanillaEncabezadoIngresos> FormatoPlanillaEncabezadoIngresos { get; set; }
    }
}

Codigo/ControlPlanilla/ControlPlanilla/Controllers/FormatoPlanillasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ControlPlanilla.Models;
using PagedList;

namespace ControlPlanilla.Controllers
{
    public class FormatoPlanillasController : AuditoriaController
    {
        private PlanillaPayControls db = new PlanillaPayControls();

        // GET: FormatoPlanillas
        public ActionResult Index()
        {
            return View(db.FormatoPlanilla.ToList());
        }

        // GET: FormatoPlanillas/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormatoPlanilla formatoPlanilla = db.FormatoPlanilla.Find(id);
            if (formatoPlanilla == null)
            {
                return HttpNotFound();
            }
            return View(formatoPlanilla);
        }

        // GET: FormatoPlanillas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FormatoPlanillas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_FORMATO,DESCRIPCION")] FormatoPlanilla formatoPlanilla)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    FormatoPlanilla guardar = new FormatoPlanilla();
                    guardar.ID_FORMATO = formatoPlanilla.ID_FORMATO;
                    guardar.DESCRIPCION = formatoPlanilla.DESCRIPCION;
                    guardar.USUA_CREA = Usuario;
                    guardar.FECH_CREA = Ahora;
                    db.FormatoPlanilla.Add(guardar);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (SystemException ex)
            {
                logRepository.CapturarTodoError(ex);
            }
            return View(formatoPlanilla);
        }

        // GET: FormatoPlanillas/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormatoPlanilla formatoPlanilla = db.FormatoPlanilla.Find(id);
            if (formatoPlanilla == null)
            {
                return HttpNotFound();
            }
            return View(formatoPlanilla);
        }

        // POST: FormatoPlanillas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_FORMATO,DESCRIPCION")] FormatoPlanilla formatoPlanilla)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var guardar = db.FormatoPlanilla.Find(formatoPlanilla.ID_FORMATO);
                    if (guardar != null)
                    {
                        guardar.DESCRIPCION = formatoPlanilla.DESCRIPCION;
                        guardar.USUA_ACTUA = Usuario;
                        guardar.FECH_ACTUA = Ahora;
                        db.Entry(guardar).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    
                }
            }
            catch (SystemException ex)
            {
                logRepository.CapturarTodoError(ex);
            }
            
            return View(formatoPlanilla);
        }

        // GET: FormatoPlanillas/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormatoPlanilla formatoPlanilla = db.FormatoPlanilla.Find(id);
            if (formatoPlanilla == null)
            {
                return HttpNotFound();
            }
            return View(formatoPlanilla);
        }

        // POST: FormatoPlanillas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            FormatoPlanilla formatoPlanilla = db.FormatoPlanilla.Find(id);
            db.FormatoPlanilla.Remove(formatoPlanilla);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        #region Ingresos
        [HttpPost]
        public PartialViewResult Ingresos(string IdFormato, int? page)
        {
            try
            {
                var lista = db.FormatoPlanillaEncabezadoIngresos.Where(c => c.ID_FORMATO == IdFormato).ToList();

                int numberpage = (page ?? 1);
                ViewBag.IdFormato = IdFormato;

                var result = lista.ToPagedList(numberpage, pageSize);
                return PartialView(result);
            }
            catch (SystemException ex)
            {
                logRepository.CapturarTodoError(ex);
            }
            return PartialView();
        }

        [HttpPost]
        public bool CrearEncabezadoIngresos([Bind(Include ="ID_CABECERA, ID_FORMATO,CHECK")]FormatoPlanillaEncabezadoIngresos encabezadoIngresos)
        {
            bool result = false;
            try
            {
                if (ModelState.IsValid)
                {
                    var guardar = new FormatoPlanillaEncabezadoIngresos();
                    guardar.ID_CABECERA = encabezadoIngresos.ID_CABECERA;
                    guardar.ID_FORMATO = encabezadoIngresos.ID_FORMATO;
                    guardar.CHECK = encabezadoIngresos.CHECK;
                    guardar.USUA_CREA = Usuario;
                    guardar.FECH_CREA = Ahora;

                    db.FormatoPlanillaEncabezadoIngresos.Add(guardar);
                    db.SaveChanges();
                    result = true;
                }
            }
            catch (SystemException ex)
            {
                logRepository.CapturarTodoError(ex);
            }
            return result;
        }
        [HttpPost]
        public bool EditarEncabezadoIngresos([Bind(Include = "ID_CABECERA, ID_FORMATO,CHECK")]FormatoPlanillaEncabezadoIngresos encabezadoIngresos)
        {
            bool result = false;
            try
            {
                if (ModelState.IsValid)
                {
                    var guardar = db.FormatoPlanillaEncabezadoIngresos.Find(encabezadoIngresos.ID_CABECERA);
                    if (guardar != null){
                        guardar.ID_CABECERA = encabezadoIngresos.ID_CABECERA;
                        guardar.CHECK = encabezadoIngresos.CHECK;
                        guardar.USUA_CREA = Usuario;
                        guardar.FECH_CREA = Ahora;

                        db.Entry(guardar).State = EntityState.Modified;
                        db.SaveChanges();
                        result = true;
                    }
                }
            }
            catch (SystemException ex)
            {
                logRepository.CapturarTodoError(ex);
            }
            return result;
        }
        [HttpPost]
        public bool EliminarEncabezadoIngresos([Bind(Include = "ID_CABECERA, ID_FORMATO")]FormatoPlanillaEncabezadoIngresos encabezadoIngresos)
        {
            bool result = false;
            try
            {
                if (ModelState.IsValid)
                {
                    var remove = db.FormatoPlanillaEncabezadoIngresos.Find(encabezadoIngresos.ID_CABECERA);
                    if (remove != null)
                    {

                        db.FormatoPlanillaEncabezadoIngresos.Remove(remove);
                        db.SaveChanges();
                        result = true;
                    }
                }
            }
            catch (SystemException ex)
            {
                logRepository.CapturarTodoError(ex);
            }
            return result;
        }

        [HttpPost]
        public PartialViewResult DetallesIngresos(string Id_Formato, string Id_Cabecera, int? page)
        {
            ViewBag.PayrollControl = new SelectList(db.PayrollControl, "Code", "Name");
            try
            {
                var lista = db.FormatoPlanillaDetalleIngresos.Where(c => 
                c.ID_FORMATO == Id_Formato && c.ID_CABECERA == Id_Cabecera).ToList();

                int numberpage = (page ?? 1);

                var result = lista.ToPagedList(numberpage, pageSize);
                ViewBag.IdFormato = Id_Formato;
                ViewBag.IdCabecera = Id_Cabecera;

                return PartialView(result);
            }
            catch (SystemException ex)
            {
                logRepository.CapturarTodoError(ex);
            }
            return PartialView();
        }
        [HttpPost]
        public bool CrearDetalleIngresos([Bind(Include = "ID_CABECERA, ID_FORMATO, PayControlCode")]FormatoPlanillaDetalleIngresos detalleIngresos)
        {
            bool result = false;
            try
            {
                if (ModelState.IsValid)
                {
                    var guardar = new FormatoPlanillaDetalleIngresos();
                    guardar.ID_CABECERA = detalleIngresos.ID_CABECERA;
                    guardar.ID_FORMATO = detalleIngresos.ID_FORMATO;
                    guardar.PayControlCode = detalleIngresos.PayControlCode;
                    guardar.USUA_CREA = Usuario;

Codigo/ControlPlanilla/ControlPlanilla/Views/FormatoPlanillas/Create.cshtml
@model ControlPlanilla.Models.FormatoPlanilla

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Vista.cshtml";
}

<br />
                <h3>Crear Planilla</h3>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="col-sm-12">
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ID_FORMATO, htmlAttributes: new { @class = "control-label col-md-2" })
                                    </div>
                                </div>
                                <div class="col-sm-9">
                                    <div class="form-group">
                                        @Html.EditorFor(model => model.ID_FORMATO, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ID_FORMATO, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.DESCRIPCION, htmlAttributes: new { @class = "control-label col-md-2" })
                                </div>
                            </div>
                            <div class="col-sm-9">
                                <div class="form-group">
                                    @Html.EditorFor(model => model.DESCRIPCION, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DESCRIPCION, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            </div>


                            <div class="form-group">
                                <input type="submit" value="Guardar" class="btn btn-primary" /> |
                                @Html.ActionLink("Regresar a la Lista", "Index")
                            </div>
                        </div>
                                }
                                <br />

Codigo/ControlPlanilla/ControlPlanilla/Views/FormatoPlanillas/Details.cshtml
@model ControlPlanilla.Models.FormatoPlanilla

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Vista.cshtml";
}

<br />
                <h3>Detalle Planilla</h3>

                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.DESCRIPCION)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.DESCRIPCION)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.USUA_CREA)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.USUA_CREA)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.FECH_CREA)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.FECH_CREA)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.USUA_ACTUA)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.USUA_ACTUA)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.FECH_ACTUA)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.FECH_ACTUA)
                            </dd>

                        </dl>
                        <p>
                            @Html.ActionLink("Editar", "Edit", new { id = Model.ID_FORMATO }) |
                            @Html.ActionLink("Regresar a la Lista", "Index")
                        </p>
                    </div>
        <br />

Codigo/ControlPlanilla/ControlPlanilla/Views/FormatoPlanillas/DetallesEgresos.cshtml
@model PagedList.IPagedList<ControlPlanilla.Models.FormatoPlanillaDetalleEgresos>
@using PagedList.Mvc;
@{
    var i = 0;
}

<table class="table table-bordered table-hover">
    <thead>


        <tr>
            <th>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().PayrollControl)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            i += 1;
            <tr>
                <td>
                    @Html.EditorFor(modelitem => item.ID, new { htmlAttributes = new { @class = "form-control", @id = "ID_" + i, @posicion = i, @type = "text", @readonly = "readonly", @style = "width:80px;" } })
                </td>
                <td>
                    @Html.DropDownList("PayrollControl_" + i, new SelectList(ViewBag.PayrollControl, "Value", "Text", item.PayControlCode), htmlAttributes: new { @class = "form-control", @posicion = i })
                </td>
                <td>
                    <button class="btn btn-sm botones" onclick="EditarDetalleEgresos(this)" posicion="@i">
                        <span class="glyphicon glyphicon-floppy-save"></span>
                    </button>
                    |
                    <button class="btn btn-sm botones" onclick="EliminarDetalleEgresos(this)" posicion="@i">
                        <span class="glyphicon glyphicon-floppy-remove"></span>
                    </button>
                </td>
            </tr>
        }
        <tr>
            <td style="width:80px;">
            </td>
            <td>
                @Html.DropDownList("PayrollControl", new SelectList(ViewBag.PayrollControl, "Value", "Text"), htmlAttributes: new { @class = "form-control", @posicion = i })
            </td>
            <td>
                <button class="btn btn-sm botones" onclick="CrearDetalleEgresos()">
                    <span class="glyphicon glyphicon-floppy-save"></span>
                </button>
            </td>
        </tr>
    </tbody>
</table>
<br />
<hr />
Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Egresos", "FormatoPlanillas", new { Id_Formato = ViewBag.IdFormato, Id_Cabecera = ViewBag.IdCabecera, page }),
PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
    {

        HttpMethod = "POST",
        UpdateTargetId = "ListDetallesEgresos",
        OnSuccess = "onAjaxSuccess",
        OnFailure = "onAjaxFailure"
    }))

Codigo/ControlPlanilla/ControlPlanilla/Views/FormatoPlanillas/DetallesIngresos.cshtml
@model PagedList.IPagedList<ControlPlanilla.Models.FormatoPlanillaDetalleIngresos>
@using PagedList.Mvc;
@{
    var i = 0;
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-hover">
    <thead>


        <tr>
            <th>
                
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().PayrollControl)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            i += 1;
            <tr>
                <td>
                    @Html.EditorFor(modelitem=> item.ID, new { htmlAttributes = new { @class = "form-control", @id = "ID_" + i, @posicion = i, @type="text", @readonly="readonly", @style="width:80px;" } })
                </td>
                <td>
                    @Html.DropDownList("PayrollControl_" + i, new SelectList(ViewBag.PayrollControl, "Value", "Text", item.PayControlCode), htmlAttributes: new { @class = "form-control", @posicion = i })
                </td>
                <td>
                    <button class="btn btn-sm botones" onclick="EditarDetalleIngresos(this)" posicion="@i">
                        <span class="glyphicon glyphicon-floppy-save"></span>
                    </button>
                    |
                    <button class="btn btn-sm botones" onclick="EliminarDetalleIngresos(this)" posicion="@i">
                        <span class="glyphicon glyphicon-floppy-remove"></span>
                    </button>
                </td>
            </tr>
        }
        <tr>
            <td style="width:80px;">

            </td>
            <td>
                @Html.DropDownList("PayrollControl", new SelectList(ViewBag.PayrollControl, "Value", "Text"), htmlAttributes: new { @class = "form-control", @posicion = i })
            </td>
            <td>
                <button class="btn btn-sm botones" onclick="CrearDetalleIngresos()">
                    <span class="glyphicon glyphicon-floppy-save"></span>
                </button>
            </td>
        </tr>
    </tbody>
</table>
<br />
<hr />
Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Ingresos", "FormatoPlanillas", new { Id_Formato = ViewBag.IdFormato, Id_Cabecera=ViewBag.IdCabecera, page }),
PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
    {

        HttpMethod = "POST",
        UpdateTargetId = "ListDetalles",
        OnSuccess = "onAjaxSuccess",
        OnFailure = "onAjaxFailure"
    }))

Codigo/ControlPlanilla/ControlPlanilla/Views/FormatoPlanillas/Egresos.cshtml
@model  PagedList.IPagedList<ControlPlanilla.Models.FormatoPlanillaEncabezadoEgresos>
@using PagedList.Mvc;
@{
    var i = 0;
}

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().ID_CABECERA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().CHECK)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            i += 1;
            <tr>
                <td>
                    @Html.EditorFor(modelItem => item.ID_CABECERA, new { htmlAttributes = new { @class = "form-control", @id = "ID_CABECERA_" + i, @posicion = i } })
                </td>
                <td>
                    @Html.EditorFor(modelItem => item.CHECK, new { htmlAttributes = new { @class = "form-control", @id = "CHECK_" + i, @posicion = i } })
                </td>
                <td>
                    <button class="btn btn-sm botones" onclick="EditarEncabezadoEgresos(this)" posicion="@i">
                        <span class="glyphicon glyphicon-floppy-save"></span>
                    </button>
                    |
                    <button class="btn btn-sm botones" onclick="EliminarEncabezadoEgresos(this)" posicion="@i">
                        <span class="glyphicon glyphicon-floppy-remove"></span>
                    </button>
                    |
                    <button class="btn btn-sm dEgre botones" data-toggle="modal" data-target="abrirModalDetallesEgresos"
                            data-id="@item.ID_CABECERA">
                        <span class="glyphicon glyphicon glyphicon-modal-window"></span>
                    </button>
                </td>
            </tr>
        }
        <tr>
            <td>
                <input type="text" class="form-control" maxlength="20" id="ID_CABECERA" />
            </td>
            <td>
                <input type="number" class="form-control" min="1" id="CHECK" />
            </td>
            <td>
                <button class="btn btn-sm botones" onclick="CrearEncabezadoEgresos()">
                    <span class="glyphicon glyphicon-floppy-save"></span>
                </button>
            </td>
        </tr>
    </tbody>

</table>

<br />
<hr />
Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Egresos", "FormatoPlanillas", new { IdFormato = ViewBag.IdFormato, page }),
PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
    {

        HttpMethod = "POST",
        UpdateTargetId = "ListEgresos",
        OnSuccess = "onAjaxSuccess",
        OnFailure = "onAjaxFailure"
    }))



<script>
   function cerrarModal()
   {
            $('#abrirModalDetallesEgresos').modal('hide');
   }
   $('.dEgre').click(function (e) {
        e.preventDefault();

        IdCabecera = $(this).data('id');
        $('#myModalLabelDetalles').html( IdFormato +  " detalle de Egresos: " + IdCabecera);
       TraerDetallesEgresos();
    });
    function TraerDetallesEgresos() {

            var url = '@Url.Action("DetallesEgresos", "FormatoPlanillas")';
            var data = { ID_CABECERA: IdCabecera, ID_FORMATO: IdFormato};
            $.post(url, data).done(function (result) {
                $('#ListDetallesEgresos').html('');
                $('#ListDetallesEgresos').html(result);
                $('#abrirModalDetallesEgresos').modal('show');
            });
            //$('#abrirModalLines').modal('show');

    }

    function ActualizarDetallesEgresos() {
        var url = '@Url.Action("DetallesEgresos", "FormatoPlanillas")';
        var data = { ID_CABECERA: IdCabecera, ID_FORMATO: IdFormato};

        $.post(url, data).done(function (result) {
                $('#ListDetallesEgresos').html('');
                $('#ListDetallesEgresos').html(result);
        });
    }
     function CrearDetalleEgresos() {

            $('.botones').attr("disabled", "disabled");

            var PayCode = $('#PayrollControl').val();

            var url = '@Url.Action("CrearDetalleEgresos", "FormatoPlanillas")';

            var data =
            {
                ID_CABECERA: IdCabecera, ID_FORMATO: IdFormato, PayControlCode:PayCode
            };


            $.post(url, data).done(function (result) {
                if (result == "True") {
                    ActualizarDetallesEgresos();
                    toastr.success("Registro creado con éxito");
                    $('.botones').removeAttr("disabled", "disabled");
                }
                else {
                    toastr.error("Hubo error al crear el registro");
                }
                $('.botones').removeAttr("disabled", "disabled");
            });
    }
    function EditarDetalleEgresos(element) {
        $('.botones').attr("disabled", "disabled");
        var posicion = $(element).attr("posicion");
        var i = posicion;
        var Id=$('#ID_' + i).val();
        var PayCode = $('#PayrollControl_' + i).val();
        var url = '@Url.Action("EditarDetalleEgresos", "FormatoPlanillas")';

        var data =
            {
               ID: Id, ID_CABECERA: IdCabecera, ID_FORMATO: IdFormato, PayControlCode:PayCode
            };


            $.post(url, data).done(function (result) {
                if (result == "True") {
                    ActualizarDetallesEgresos();
                    toastr.success("Registro actualizado con éxito");
                    $('.botones').removeAttr("disabled", "disabled");
                }
                else {
                    toastr.error("Hubo error al actualizar el registro");
                }
                $('.botones').removeAttr("disabled", "disabled");
            });
    }
    function EliminarDetalleEgresos(element) {
        $('.botones').attr("disabled", "disabled");
        var posicion = $(element).attr("posicion");
        var i = posicion;
        var Id=$('#ID_' + i).val();
        var PayCode = $('#PayrollControl_'+i).val();
        var url = '@Url.Action("EliminarDetalleEgresos", "FormatoPlanillas")';

        var data =
            {
              ID:Id, ID_CABECERA: IdCabecera, ID_FORMATO: IdFormato, PayControlCode:PayCode
            };


            $.post(url, data).done(function (result) {
                if (result == "True") {
                    ActualizarDetallesEgresos();
                    toastr.success("Registro actualizado con éxito");
                    $('.botones').removeAttr("disabled", "disabled");
                }
                else {
                    toastr.error("Hubo error al actualizar el registro");
                }
                $('.botones').removeAttr("disabled", "disabled");
            });
    }

</script>